#ifndef DEFAULTS_H
#define DEFAULTS_H

#ifdef USE_ALSA
#define DEFAULT_DEVICE "default"
#endif
#define DEFAULT_BUFFER 2

#ifdef LINUX
#define DEFAULT_ADDR "::"
#else
#define DEFAULT_ADDR "0.0.0.0"
#endif
#define DEFAULT_PORT 50050
#define DEFAULT_FRAME 120
#define DEFAULT_JITTER 4

#define DEFAULT_RATE 48000
#define DEFAULT_INPUTCHANNELS 1
#define DEFAULT_OUTPUTCHANNELS 2
#define DEFAULT_BITRATE 128

#define DEFAULT_VERBOSE 1

#define STATS_INTERVAL_MS 5000
#define TIMED_SELECT_INTERVAL 1
#endif
